name: Register
main: me.lucasemanuel.register.Main
version: 1.5

commands:
  reg:
    description: Used to register to the forum.
    usage: /<command> <e-post> <losenord>
    permission: register.register
  mpromote:
    description: Promotes a user
    usage: /<command> <spelarnamn> <rank>
    permission: register.promote
  mdemote:
    description: Demotes a user
    usage: /<command> <spelarnamn> <rank>
    permission: register.demote