name: Register
main: me.lucasemanuel.register.Main
version: 1.4

commands:
  reg:
    description: Used to register to the forum.
    usage: /<command> <e-post> <losenord>
    permission: register.register
  promote:
    description: Promotes a user
    usage: /<command> <playername>
    permission: register.promote
  demote:
    description: Demotes a user
    usage: /<command> <playername>
    permission: register.demote